######################################################################
# Automatically generated by qmake (3.0) Thu Sep 19 22:00:52 2013
######################################################################
QT += widgets

TEMPLATE = app
TARGET = block
INCLUDEPATH += .
QMAKE_CXX = clang++
QMAKE_CXXFLAGS = -std=c++11

# Input
SOURCES += main.cc \
    figura.cc \
    tablero.cc

HEADERS += \
    tablero.hpp \
    figura.hpp
