mulmat: mulmat.cc
	g++ -o mulmat mulmat.cc 

mulmat-op: mulmat.cc
	g++ -o mulmat-op mulmat.cc -O3

multmat: multmat.cc
	g++ -O3 -o multmat multmat.cc 

multmat-c++11: multmat-c++11.cc
	g++-4.8 -Wall -std=c++11 -O3 -o multmat-c++11 multmat-c++11.cc 
